name: Make commit!

on:
  schedule:
    - cron: '*/2 * * * *' # Every day at 16:30
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Git status
      run: git status
    - name: Action
      run: echo "What is the price of gold?" >> CHANGELOG
    - name: Commit & push
      run: git add . && git commit -m "Hmm..."
    - uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.REPO_TOKEN }}
      
