name: Make commit!

on:
  schedule:
    - cron: '5 * * * *' # Every day at 16:30
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Git status
      run: git status
    - name: Action
      run: echo "What is the price of gold?" >> CHANGELOG
    - name: Commit & push
      run: git add . && git commit -m "Hmm..." && git push origin master
      
#     - name: Run a multi-line script
#       run: |
#         echo Add other actions to build,
#         echo test, and deploy your project.
