name: Automate it!

on:
  schedule:
    - cron: '42 9 * * *' # Every day
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Git status
      run: git status
    - name: Action
      run: echo "What is the price of gold?" >> CHANGELOG
    - name: Commit files
      run: |
        git config --local user.email "zhilyaev.dmitriy@gmail.com"
        git config --local user.name "zhilyaev"
        git commit -m "WIP: hmm..." -a
    - uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.REPO_TOKEN }}
      
